### ISSUE TITLE
"TypeError: remove() argument 1 must be string, not None"

### ISSUE THREAD

**Issue by peripatetes** [pts/pdfsizeopt#106]
Ran into this error on [the second file I tried pdfsizeopt on](http://www.math.ucdavis.edu/~tracy/courses/math22B/22BBook.pdf):

```
[~80 lines of console output omitted]
info: optimizing 17 images of 38034482 bytes in total
info: executing image converter sam2p_np: sam2p -j:quiet -pdf:2 -c zip:1:9 -s Gray1:Indexed1:Gray2:Indexed2:Rgb1:Gray4:Indexed4:Rgb2:Gray8:Indexed8:Rgb4:Rgb8:stop -- C:\Users\username\AppData\Local\Temp\psotmp.6824.img-35.parse.png C:\Users\username\AppData\Local\Temp\psotmp.6824.img-35.sam2p-np.pdf
info: loading image from: C:\Users\username\AppData\Local\Temp\psotmp.6824.img-35.sam2p-np.pdf
info: loading PDF from: C:\Users\username\AppData\Local\Temp\psotmp.6824.img-35.sam2p-np.pdf
info: loaded PDF of 1489137 bytes
info: separated to 5 objs + xref + trailer
info: parsed 5 objs
info: loaded PNG IDAT of 1488423 bytes
Traceback (most recent call last):
  File "C:\Users\username\Downloads\pdf\pdfsizeopt_win32exec-v6\pdfsizeopt_win32exec\python26.zip\runpy.py", line 122, in _run_module_as_main
  File "C:\Users\username\Downloads\pdf\pdfsizeopt_win32exec-v6\pdfsizeopt_win32exec\python26.zip\runpy.py", line 34, in _run_code
  File "C:\Users\username\Downloads\pdf\pdfsizeopt_win32exec-v6\pdfsizeopt.single\__main__.py", line 1, in <module>
  File "C:\Users\username\Downloads\pdf\pdfsizeopt_win32exec-v6\pdfsizeopt.single\m.py", line 6, in <module>
  File "C:\Users\username\Downloads\pdf\pdfsizeopt_win32exec-v6\pdfsizeopt.single\pdfsizeopt\main.py", line 5612, in main
  File "C:\Users\username\Downloads\pdf\pdfsizeopt_win32exec-v6\pdfsizeopt.single\pdfsizeopt\main.py", line 4366, in OptimizeImages
TypeError: remove() argument 1 must be string, not None
```
I'm running Windows 10 and the latest pdfsizeopt.single (83c8ee1).

**Comment by pts** [comment]
Thank you for reporting this! Fixed in d3c4bc8816930b814c30015102e30c8d147ec18b. Please install pdfsizeopt again as documented on https://github.com/pts/pdfsizeopt (it's enough to upgrade `pdfsizeopt.single`) and retry.
