### ISSUE TITLE
if --use-image-optimizer is used pdfsizeopt.single terminates with UnboundLocalError: local variable 'np_image_bpc' referenced before assignment

### ISSUE THREAD

**Issue by davdittrich** [pts/pdfsizeopt#107]
If I use --use-image-optimizer pdfsizeopt terminates with

Traceback (most recent call last):
  File "/proc/self/exe/runpy.py", line 162, in _run_module_as_main
  File "/proc/self/exe/runpy.py", line 72, in _run_code
  File "/home/dd/bin/pdfsizeopt/pdfsizeopt.single/__main__.py", line 1, in <module>
  File "/home/dd/bin/pdfsizeopt/pdfsizeopt.single/m.py", line 6, in <module>
  File "/home/dd/bin/pdfsizeopt/pdfsizeopt.single/pdfsizeopt/main.py", line 5618, in main
  File "/home/dd/bin/pdfsizeopt/pdfsizeopt.single/pdfsizeopt/main.py", line 4409, in OptimizeImages
UnboundLocalError: local variable 'np_image_bpc' referenced before assignment

**Comment by davdittrich** [comment]
It seems there is an indentation issue main.py.

**Comment by davdittrich** [comment]
Line 7694 and the following 60 lines in main.py need to be indented by an additional 2 spaces.

**Comment by davdittrich** [comment]
But then the temp-files are not removed anymore. I don't understand the code well enough to immediately see what's wrong / how to fix this.

**Comment by pts** [comment]
Thank you for reporting this! I'll fix it soon.

In the meantime, as a workaround, please an earlier version of `pdfsizeopt.single`.

**Comment by pts** [comment]
Thank you for reporting this! Fixed in 5a42db5bef4df1652adb3ef49a9d14bcb58442eb.
