### ISSUE TITLE
Problem trying to compress a pdf file

### ISSUE THREAD

**Issue by JhonGH** [pts/pdfsizeopt#18]
Hello,
I have a problem trying to compress a pdf file created with PDFSharp.

These are the console messages:

```
info: This is pdfsizeopt ZIP rUNKNOWN size=111340.
info: prepending to PATH: C:\pdfsizeopt\pdfsizeopt_win32exec
info: loading PDF from: C:\pdfsizeopt\pdf_in\_TRASF_20170502\3489189.pdf
info: loaded PDF of 90961 bytes
info: found 25 obj offsets and 1 obj streams in xref stream
info: separated to 23 objs + xref + trailer
info: found 0 Type1 fonts loaded
info: found 0 Type1C fonts loaded
info: will optimize image XObject 6; orig width=1670 height=2325 colorspace=/Dev
iceGray bpc=1 filter=[/JBIG2Decode] dp=0 size=29101 gs_device=pngmono
info: will optimize image XObject 11; orig width=1671 height=2335 colorspace=/De
viceGray bpc=1 filter=[/JBIG2Decode] dp=0 size=8876 gs_device=pngmono
info: will optimize image XObject 16; orig width=1671 height=2327 colorspace=/De
viceGray bpc=1 filter=[/JBIG2Decode] dp=0 size=28280 gs_device=pngmono
info: will optimize image XObject 21; orig width=1671 height=2338 colorspace=/De
viceGray bpc=1 filter=[/JBIG2Decode] dp=0 size=22849 gs_device=pngmono
info: optimizing 4 images of 89106 bytes in total
info: writing ImageRenderer (88949 image bytes) to: C:\pdfsizeopt\pdf_out\psotmp
.5608.conv.pngmono.tmp.ps
info: using Ghostscript "C:\pdfsizeopt\pdfsizeopt_win32exec\pdfsizeopt_gswin\gsw
in32c.exe": GPL Ghostscript 9.21 (2017-03-16)
info: executing ImageRenderer with Ghostscript: "C:\pdfsizeopt\pdfsizeopt_win32e
xec\pdfsizeopt_gswin\gswin32c.exe" -q -dNOPAUSE -dBATCH -sDEVICE=pngmono -sOutpu
tFile=C:\pdfsizeopt\pdf_out\psotmp.5608.img-%04d.pngmono.tmp.png -f C:\pdfsizeop
t\pdf_out\psotmp.5608.conv.pngmono.tmp.ps
Traceback (most recent call last):
  File "C:\pdfsizeopt\pdfsizeopt_win32exec\python26.zip\runpy.py", line 122, in
_run_module_as_main
  File "C:\pdfsizeopt\pdfsizeopt_win32exec\python26.zip\runpy.py", line 34, in _
run_code
  File "C:\pdfsizeopt\pdfsizeopt.single\__main__.py", line 1, in <module>
  File "C:\pdfsizeopt\pdfsizeopt.single\mainrun.py", line 10, in <module>
  File "C:\pdfsizeopt\pdfsizeopt.single\pdfsizeopt\main.py", line 8597, in main
  File "C:\pdfsizeopt\pdfsizeopt.single\pdfsizeopt\main.py", line 6726, in Optim
izeImages
File "C:\pdfsizeopt\pdfsizeopt.single\pdfsizeopt\main.py", line 6431, in Rende
rImages
ValueError: popen() arg 3 must be -1
```

I don't have problems with pdfs created by other applications.
Could you someone help me please?
Thank you!

**Comment by pts** [comment]
Thank you for reporting this! Fixed in db3e079a8ba76bd513185a25069d5fff380f10ab . Please upgrade to the latest pdfsizeopt and ejoy the fix.
