### ISSUE TITLE
ValueError: Char not allowed in PostScript name: '{'

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#28]
Hi, @pts.

Here is crash with a potentially non-compliant file, also generated by pdfTeX:

(...)

    Type1CParser: using interpreter GPL Ghostscript 921 20170316
    Type1CParser: all OK
    info: parsed 18 Type1C fonts
    Traceback (most recent call last):
      File "/home/rbrito/Downloads/pdfsizeopt/pdfsizeopt", line 37, in <module>
        sys.exit(main.main(sys.argv))
      File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 8603, in main
        do_regenerate_all_fonts=do_regenerate_all_fonts)
      File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 6099, in OptimizeType1CFonts
        do_keep_font_optionals=do_keep_font_optionals)
      File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 5982, in _ProcessType1CFonts
        do_double_check_type1c_output=do_double_check_type1c_output)
      File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 5648, in SerializeType1CFonts
        AppendSerializedPs(parsed_fonts[obj_num], output)
      File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 5623, in AppendSerializedPs
        AppendSerializedPs(value[item], output)
      File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 5635, in AppendSerializedPs
        value = pdf_to_ps_name(value)
      File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 1830, in PdfToPsName
        'Char not allowed in PostScript name: %r' % match.group())
    ValueError: Char not allowed in PostScript name: '{'

I don't remember where I got the file, but as I don't believe that the file is that secret, I am attaching it here. I would give it a low priority, though...

Thanks,

Rogério.
[dft-fft.pdf](https://github.com/pts/pdfsizeopt/files/1247609/dft-fft.pdf)

**Comment by pts** [comment]
Thank you for reporting this!

Fixed in f38f064d58c1e3e3cc4f0200366fc59d948617ef.

Also the attached dft-fft.pdf file exposed these warnings:

```
warning: cannot parse obj 703: pdfsizeopt.main.PdfIndirectLengthError: missing obj for indirect /Length 705 0 R at ofs=45945
warning: cannot parse obj 1267: pdfsizeopt.main.PdfIndirectLengthError: missing obj for indirect /Length 1269 0 R at ofs=115493
```

Processing of indirect /Length of this file was fixed in e9f9972b3758af89266d8733c43035739df3e0d5.

**Comment by rbrito** [comment]
Thank you so much for this, even though this was a (probably) malformed file.

**Comment by pts** [comment]
The CFF specification strongly recommends against `{` and `}` in the `/FontName`, but such a PDF file (dft-fft.pdf) apparently worked in the PDF viewers I had access to, so it was worth fixing this in pdfsizeopt.
