### ISSUE TITLE
values_dict in lib/pdfsizeopt/main.py lines 6327 and 6329 must be cmd_values_dict

### ISSUE THREAD

**Issue by davdittrich** [pts/pdfsizeopt#38]
pdfsizeopt throws an error with png optimization:

```
info: loaded PNG IDAT of 4796 bytes
Traceback (most recent call last):
  File "/home/dd/bin/pdfsizeopt/pdfsizeopt", line 37, in <module>
    sys.exit(main.main(sys.argv))
  File "/home/dd/bin/pdfsizeopt/lib/pdfsizeopt/main.py", line 8955, in main
    pdf.OptimizeImages(img_cmd_patterns=img_cmd_patterns)
  File "/home/dd/bin/pdfsizeopt/lib/pdfsizeopt/main.py", line 7111, in OptimizeImages
    return_none_if_status=return_none_if_status)
  File "/home/dd/bin/pdfsizeopt/lib/pdfsizeopt/main.py", line 6327, in ConvertImage
    values_dict['pngout_gray_flags'] = '-c0 '
NameError: global name 'values_dict' is not defined
```

The error is solved by changing "values_dict" in lib/pdfsizeopt/main.py lines 6327 and 6329 to "cmd_values_dict"

**Comment by pts** [comment]
Thank you for reporting this!

Fixed in 8525ac7d13b2ba54b8d5985cbef71d4618cf1d91.
