### ISSUE TITLE
Problem when calling Multivalent on files

### ISSUE THREAD

**Issue by rbrito** [pts/pdfsizeopt#40]
It seems that calling Multivalent got broken sometime in the last few days.

If I use the same p040.pdf that I uploaded to the last issue, but now enabling Multivalent, then I get the following error:

```
(...)
info: loading image from: psotmp.19025.img-12.sam2p-np.pdf
info: loading PDF from: psotmp.19025.img-12.sam2p-np.pdf
info: loaded PDF of 27097 bytes
info: separated to 5 objs + xref + trailer
info: parsed 5 objs
info: loaded PNG IDAT of 26018 bytes and PLTE of 171 bytes
info: executing image converter sam2p_pr: sam2p -c zip:15:9 -- psotmp.19025.img-12.parse.png psotmp.19025.img-12.sam2p-pr.png
This is sam2p .
Available Loaders: PS PDF JAI PNG JPEG TIFF PNM BMP GIF LBM XPM PCX TGA.
Available Appliers: XWD Meta Empty BMP PNG TIFF6 TIFF6-JAI JPEG-JAI JPEG PNM GIF89a+LZW XPM PSL1C PSL23+PDF PSL2+PDF-JAI P-TrOpBb.
sam2p: Notice: PNM: loaded alpha, but no transparent pixels
sam2p: Notice: job: read InputFile: psotmp.19025.img-12.parse.png
sam2p: Notice: applyProfile: applied OutputRule #12
sam2p: Notice: job: written OutputFile: psotmp.19025.img-12.sam2p-pr.png
Success.
info: loading image from: psotmp.19025.img-12.sam2p-pr.png
info: loaded PNG IDAT of 24173 bytes and PLTE of 171 bytes
info: optimized image XObject 12 file_name=psotmp.19025.img-12.sam2p-pr.png size=24569 (60%) methods=sam2p_pr:24569,sam2p_np:26372,#orig:40949,parse:40949
info: saved 16380 bytes (40%) on optimizable images
info: optimized 5 streams, kept 5 #orig
info: eliminated 3 unused objs in 3 classes
info: saving PDF with 14 objs with Multivalent to: p040.psom.pdf
info: writing Multivalent input PDF: psotmp.19025.conv.mi.tmp.pdf
info: generated object stream of 1097 bytes in 8 objects (23%)
Traceback (most recent call last):
  File "/home/rbrito/Downloads/pdfsizeopt/pdfsizeopt", line 41, in <module>
    sys.exit(main.main(sys.argv, script_dir=script_dir))
  File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 8941, in main
    not f.do_decompress_most_streams))
  File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 8495, in Save
    multivalent_compress_command=multivalent_compress_command)
  File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 8382, in _RunMultivalent
    may_obj_heads_contain_comments=may_obj_heads_contain_comments)
  File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 5017, in AppendSerializedPdf
    pdf_obj.Set('Subtype', 'ImagE')
  File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 1478, in Set
    value = self.ParseSimpleValue(value)
  File "/home/rbrito/Downloads/pdfsizeopt/lib/pdfsizeopt/main.py", line 1807, in ParseSimpleValue
    raise PdfTokenParseError('Syntax error in %r' % data)
pdfsizeopt.main.PdfTokenParseError: Syntax error in 'ImagE'
```

The command line in use here was:

    ~/Downloads/pdfsizeopt/pdfsizeopt --use-pngout=no --use-multivalent=yes p040.pdf

For convenience, here goes p040.pdf again.

[p040.pdf](https://github.com/pts/pdfsizeopt/files/1293983/p040.pdf)

Thanks a lot for the work on pdfsizeopt, BTW.

**Comment by pts** [comment]
Thank you for submitting this bug report!

Fixed it 93de33816ace6ef8b3f91cffecd161ad6018f25c. It was a long-standing silly bug. Previously it was not detected, because the parsing in PdfObj.__init__ wasn't strict enough to detect it.

Also this bug report revealed an inconsistency how CompressValue was called to produce safe and unsafe PDF token sequences. I've fixed that in 1acf84526b8bf5779fb684f236ea6503efb82395.

Oddly enough, for this input, the PDF with Multivalent (p040.psom.pdf) is 27 bytes larger than without Multivalent.
