### ISSUE TITLE
pdfsizeopt --stats fails

### ISSUE THREAD

**Issue by alexsavio** [pts/pdfsizeopt#43]
Following your instructions in MacOS, I then test the '--stats' flag:
```
./pdfsizeopt --stats deptest.pdf
```

This is what I get:
```
info: This is pdfsizeopt ZIP rUNKNOWN size=66098.
info: computing statistics for PDF: deptest.pdf
info: PDF size is 36080 bytes
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.13_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "./pdfsizeopt.single/__main__.py", line 1, in <module>
  File "./pdfsizeopt.single/m.py", line 6, in <module>
  File "./pdfsizeopt.single/pdfsizeopt/main.py", line 5194, in main
  File "./pdfsizeopt.single/pdfsizeopt/main.py", line 4625, in ComputePdfStatistics
  File "./pdfsizeopt.single/pdfsizeopt/main.py", line 4507, in ParseSequentially
AssertionError
```

**Comment by pts** [comment]
Thank you for reporting this bug! Fixed in bded3ac6c41d3160cf8e964ebcca8d43855dd518.
