### ISSUE TITLE
AssertionError processing PDF with "0 objs, 0 streams"

### ISSUE THREAD

**Issue by sbibauw** [pts/pdfsizeopt#77]
The following PDF generates an AssertionError in Python: [Lecture 1b - Deep Neural Networks Are Our Friends.pdf](https://github.com/pts/pdfsizeopt/files/1857834/Lecture.1b.-.Deep.Neural.Networks.Are.Our.Friends.pdf)

Here is the output:

```
info: This is pdfsizeopt ZIP rUNKNOWN size=67742.
info: prepending to PATH: /usr/local/Cellar/pdfsizeopt/HEAD-47a0340/bin
info: loading PDF from: Lecture 1b - Deep Neural Networks Are Our Friends.pdf
info: loaded PDF of 3566211 bytes
info: separated to 1648 objs + xref + trailer
info: parsed 1648 objs
info: eliminated 1648 unused objs, depth=1
info: found 0 Type1 fonts loaded
info: found 0 Type1C fonts loaded
info: optimized 0 streams, kept
warning: obj 4 missing, referenced by objs ['trailer']...
warning: obj 5 missing, referenced by objs ['trailer']...
info: compressed 0 streams, kept 0 of them uncompressed
info: saving PDF with 0 objs to: Lecture 1b - Deep Neural Networks Are Our Friends.pso.pdf
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/bin/../Cellar/pdfsizeopt/HEAD-47a0340/bin/pdfsizeopt/__main__.py", line 1, in <module>
  File "/usr/local/bin/../Cellar/pdfsizeopt/HEAD-47a0340/bin/pdfsizeopt/m.py", line 6, in <module>
  File "/usr/local/bin/../Cellar/pdfsizeopt/HEAD-47a0340/bin/pdfsizeopt/pdfsizeopt/main.py", line 5499, in main
  File "/usr/local/bin/../Cellar/pdfsizeopt/HEAD-47a0340/bin/pdfsizeopt/pdfsizeopt/main.py", line 5166, in Save
  File "/usr/local/bin/../Cellar/pdfsizeopt/HEAD-47a0340/bin/pdfsizeopt/pdfsizeopt/main.py", line 2996, in _AssertBeforeWrite
AssertionError
zsh: exit 1     pdfsizeopt "Lecture 1b - Deep Neural Networks Are Our Friends.pdf"
```

(Note: As I am processing a lot of files in batch, I will be reporting issues FYI, but this is no big deal in my case, so do not worry too much about those bugs. They can very well wait ;-))

**Comment by pts** [comment]
Thank you for reporting this! Fixed in e4c50c873b3be112444e79f33cbb1a6e781d32ec. Please upgrade to the latest pdfsizeopt, it should work.

The reason why it didn't work is that PdfObj.ParseTrailer was buggy: it didn't simplify the PDF token sequence. The bug was triggered by newline (`\n`) characters in the PDF trailers, which should have been turned to spaces by simplification.
