### ISSUE TITLE
pdfsizeopt-2017-09-03d fails on deptest.pdf

### ISSUE THREAD

**Issue by sbibauw** [pts/pdfsizeopt#82]
The executable provided in the source code with the last release for macOS ([2017-09-03d](https://github.com/pts/pdfsizeopt/releases/tag/2017-09-03d)) is failing on the `deptest.pdf`, with the following output:

```
info: This is pdfsizeopt rUNKNOWN size=347920.
info: prepending to PATH: ./pdfsizeopt_libexec
info: loading PDF from: deptest.pdf
info: loaded PDF of 36080 bytes
info: separated to 25 objs + xref + trailer
info: found 2 Type1 fonts loaded
info: writing Type1CConverter (31666 font bytes) to: psotmp.7504.conv.tmp.ps
info: using Ghostscript ./pdfsizeopt_libexec/pdfsizeopt_gs/gs: GPL Ghostscript 9.05 (2012-02-08)
info: executing Type1CConverter with Ghostscript: ./pdfsizeopt_libexec/pdfsizeopt_gs/gs -q -P- -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dPDFSETTINGS=/printer -dColorConversionStrategy=/LeaveColorUnchanged -sOutputFile=psotmp.7504.conv.tmp.pdf -f psotmp.7504.conv.tmp.ps
Type1CConverter: using interpreter GPL Ghostscript 905 20120208
Type1CConverter: converting font /JVWJQI+LMRoman10-Regular to /Obj0000000010
Type1CConverter: converting font /MFCZJC+LMRoman10-Regular to /Obj0000000022
Type1CConverter: all OK
info: loading PDF from: psotmp.7504.conv.tmp.pdf
info: loaded PDF of 4397 bytes
info: separated to 16 objs + xref + trailer
info: found 2 fonts in GS output
info: optimized total Type1 font size 31658 to Type1C font size 902 (3%)
info: optimized Type1 font XObject 10,13: new size=658 (4%)
info: optimized Type1 font XObject 22,25: new size=708 (4%)
info: found 2 Type1C fonts loaded
info: writing Type1CParser (891 font bytes) to: psotmp.7504.conv.parse.tmp.ps
info: executing Type1CParser with Ghostscript: ./pdfsizeopt_libexec/pdfsizeopt_gs/gs -q -P- -dNOPAUSE -dBATCH -sDEVICE=nullpage -sDataFile=psotmp.7504.conv.parsedata.tmp.ps -f psotmp.7504.conv.parse.tmp.ps
Type1CParser: using interpreter GPL Ghostscript 905 20120208
Type1CParser: all OK
info: parsed 2 Type1C fonts
info: merged fonts ['/JVWJQI+LMRoman10-Regular', '/MFCZJC+LMRoman10-Regular'], reduced char count from 4 to 3 (75%)
info: writing Type1CGenerator (1475 bytes in 1 fonts) to: psotmp.7504.conv.gen.tmp.ps
info: executing Type1CGenerator with Ghostscript: ./pdfsizeopt_libexec/pdfsizeopt_gs/gs -q -P- -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dPDFSETTINGS=/printer -dColorConversionStrategy=/LeaveColorUnchanged -sOutputFile=psotmp.7504.conv.gen.tmp.pdf -f psotmp.7504.conv.gen.tmp.ps
Type1CGenerator: using interpreter GPL Ghostscript 905 20120208
Type1CGenerator: all OK
info: loading PDF from: psotmp.7504.conv.gen.tmp.pdf
info: loaded PDF of 3536 bytes
info: separated to 14 objs + xref + trailer
info: found 1 fonts loaded
info: optimized Type1C fonts to form 1314 bytes to 756 bytes (58%)
info: uninlined 1 images, saved -81 bytes
info: will optimize image XObject 9; orig width=100 height=100 colorspace=/DeviceGray bpc=1 inv=False filter=/FlateDecode dp=1 size=413 gs_device=pngmono
info: saving PNG to psotmp.7504.img-9.parse.png
info: written 226 bytes to PNG
info: will optimize image XObject 26; orig width=100 height=100 colorspace=/DeviceGray bpc=1 inv=False filter=/CCITTFaxDecode dp=1 size=913 gs_device=pngmono
info: optimizing 2 images of 1326 bytes in total
info: writing ImageRenderer (920 image bytes) to: psotmp.7504.conv.pngmono.tmp.ps
info: executing ImageRenderer with Ghostscript: ./pdfsizeopt_libexec/pdfsizeopt_gs/gs -q -P- -dNOPAUSE -dBATCH -sDEVICE=pngmono -sOutputFile='psotmp.7504.img-%04d.pngmono.tmp.png' -f psotmp.7504.conv.pngmono.tmp.ps
ImageRenderer: rendering image XObject 26 width=100 height=100 bpc=1 colorspace=/DeviceGray filter=/CCITTFaxDecode decodeparms=<< /K 0 /Columns 100 >> device=pngmono
ImageRenderer: all OK
info: loading image from: psotmp.7504.img-0001.pngmono.tmp.png
info: loaded PNG IDAT of 171 bytes
info: executing image converter sam2p_np: sam2p -pdf:2 -c zip:1:9 -s Gray1:Indexed1:Gray2:Indexed2:Rgb1:Gray4:Indexed4:Rgb2:Gray8:Indexed8:Rgb4:Rgb8:stop -- psotmp.7504.img-9.parse.png psotmp.7504.img-9.sam2p-np.pdf
This is sam2p 0.49.3.
Available Loaders: PS PDF JAI PNG JPEG TIFF PNM BMP GIF LBM XPM PCX TGA.
Available Appliers: XWD Meta Empty BMP PNG TIFF6 TIFF6-JAI JPEG-JAI JPEG PNM GIF89a+LZW XPM PSL1C PSL23+PDF PSL2+PDF-JAI P-TrOpBb.
sam2p: Notice: PNM: loaded alpha, but no transparent pixels
sam2p: Notice: job: read InputFile: psotmp.7504.img-9.parse.png
sam2p: Notice: writeTTT: using template: p02
sam2p: Notice: applyProfile: applied OutputRule #0 using applier PSL23+PDF
sam2p: Notice: job: written OutputFile: psotmp.7504.img-9.sam2p-np.pdf
Success.
info: loading image from: psotmp.7504.img-9.sam2p-np.pdf
info: loading PDF from: psotmp.7504.img-9.sam2p-np.pdf
info: loaded PDF of 874 bytes
info: separated to 5 objs + xref + trailer
info: loaded PNG IDAT of 167 bytes
info: executing image converter sam2p_pr: sam2p -c zip:15:9 -- psotmp.7504.img-9.parse.png psotmp.7504.img-9.sam2p-pr.png
This is sam2p 0.49.3.
Available Loaders: PS PDF JAI PNG JPEG TIFF PNM BMP GIF LBM XPM PCX TGA.
Available Appliers: XWD Meta Empty BMP PNG TIFF6 TIFF6-JAI JPEG-JAI JPEG PNM GIF89a+LZW XPM PSL1C PSL23+PDF PSL2+PDF-JAI P-TrOpBb.
sam2p: Notice: PNM: loaded alpha, but no transparent pixels
sam2p: Notice: job: read InputFile: psotmp.7504.img-9.parse.png
sam2p: Notice: applyProfile: applied OutputRule #2 using applier PNG
sam2p: Notice: job: written OutputFile: psotmp.7504.img-9.sam2p-pr.png
Success.
info: loading image from: psotmp.7504.img-9.sam2p-pr.png
info: loaded PNG IDAT of 226 bytes
info: executing image converter jbig2: jbig2 -p psotmp.7504.img-9.sam2p-pr.png >psotmp.7504.img-9.jbig2
info: executing image converter pngout: pngout -force psotmp.7504.img-9.sam2p-pr.png psotmp.7504.img-9.pngout.png
 In:     283 bytes               psotmp.7504.img-9.sam2p-pr.png -c0 -f5 -d1
Out:     238 bytes               psotmp.7504.img-9.pngout.png -c3 -f0 -d1, 2 colors
Chg:     -45 bytes ( 84% of original)
info: loading image from: psotmp.7504.img-9.pngout.png
info: loaded PNG IDAT of 163 bytes and PLTE of 6 bytes
info: optimized image XObject 9 file_name=psotmp.7504.img-9.sam2p-np.pdf size=342 (83%) methods=sam2p_np:342,jbig2:355,pngout:398,parse:404,#orig:413,sam2p_pr:461
info: executing image converter sam2p_np: sam2p -pdf:2 -c zip:1:9 -s Gray1:Indexed1:Gray2:Indexed2:Rgb1:Gray4:Indexed4:Rgb2:Gray8:Indexed8:Rgb4:Rgb8:stop -- psotmp.7504.img-0001.pngmono.tmp.png psotmp.7504.img-26.sam2p-np.pdf
This is sam2p 0.49.3.
Available Loaders: PS PDF JAI PNG JPEG TIFF PNM BMP GIF LBM XPM PCX TGA.
Available Appliers: XWD Meta Empty BMP PNG TIFF6 TIFF6-JAI JPEG-JAI JPEG PNM GIF89a+LZW XPM PSL1C PSL23+PDF PSL2+PDF-JAI P-TrOpBb.
sam2p: Notice: PNM: loaded alpha, but no transparent pixels
sam2p: Notice: job: read InputFile: psotmp.7504.img-0001.pngmono.tmp.png
sam2p: Notice: writeTTT: using template: p02
sam2p: Notice: applyProfile: applied OutputRule #0 using applier PSL23+PDF
sam2p: Notice: job: written OutputFile: psotmp.7504.img-26.sam2p-np.pdf
Success.
info: loading image from: psotmp.7504.img-26.sam2p-np.pdf
info: loading PDF from: psotmp.7504.img-26.sam2p-np.pdf
info: loaded PDF of 874 bytes
info: separated to 5 objs + xref + trailer
info: loaded PNG IDAT of 167 bytes
info: using already processed image for obj 26
Traceback (most recent call last):
  File "./pdfsizeopt", line 40, in <module>
    sys.exit(main.main(sys.argv, script_dir=script_dir))
  File "./lib/pdfsizeopt/main.py", line 8423, in main
    pdf.OptimizeImages(img_cmd_patterns=img_cmd_patterns)
  File "./lib/pdfsizeopt/main.py", line 6613, in OptimizeImages
    os.remove(pr_file_name)
OSError: [Errno 2] No such file or directory: 'psotmp.7504.img-9.sam2p-pr.png'
zsh: exit 1     ./pdfsizeopt deptest.pdf
```
Note that it does work perfectly of course, including with the provided `libexec` binaries this 2017-09-03d release, with the current `pdfsizeopt.single`, as well as with the `single` binary provided in the [last Linux release](https://github.com/pts/pdfsizeopt/archive/2017-10-11b.tar.gz).

My recommendation would be to release a new mac version, possibly with exactly the same binaries packed into `libexec`, and only the current version of `pdfsizeopt.single`... But it is also perfectly fine to leave things as is, since, when installed following the installation instructions (i.e., downloading the last version of `pdfsizeopt.single` with `curl`), it works fine. :-)

**Comment by pts** [comment]
Thank you for reporting this, and thank you for providing all the details to reproduce the problem!

> The executable provided in the source code with the last release for macOS ([2017-09-03d](https://github.com/pts/pdfsizeopt/releases/tag/2017-09-03d)) is failing on the `deptest.pdf`

Indeed.

The *Source code* download link shouldn't be used for installing pdfsizeopt. Unfortunately it's not possible to remove this link (GitHub always displays it), so I've just expanded the description text with a link to the installation instructions and with warning stating that the *Source code* link shouldn't be used.

> release a new mac version

Doing so would take away too much of my free time unnecessarily, because I would need to repeat it 3 times (Windows, Linux and macOS) each time a push a new commit with changes to `pdfsizeopt.single`.

If you have any other recommendation which would make installation less confusing for a new user, please let me know.
